example of using updated SupersetAPI policies in cocosign
scribe-security/jenkins-pki-example pull request #2
Opened 2023-08-28 12:35 UTC by cppvik

Rego policy updated to support the new version of superset policy api

2023-08-29 23:08 UTC, eram requested changes

2023-08-29 23:08 UTC, eram commented on .valint_pass.yaml
> +                username: SMZ5qKFXMg7oe6ZmJjRv4BHzxXEKdqmX
Not creds in code pls

2023-08-29 23:08 UTC, eram commented on .valint.rego
> +  # policy.images.allow
Do we need comments in code?

2023-08-30 05:56 UTC, cppvik commented on .valint.rego
> +  # policy.images.allow
cocosign is able to support multiple built-in policies on superset, but right now only one of them is working and documented. These comments show how to run multiple built-in policies in the future.

2023-08-30 05:56 UTC, cppvik commented on .valint_pass.yaml
> +                username: SMZ5qKFXMg7oe6ZmJjRv4BHzxXEKdqmX
sure, sorry

2023-08-30 05:59 UTC, cppvik commented
To pass the tests we need to merge [this](https://github.com/scribe-security/cocosign/pull/56) first.

2023-11-29 16:51 UTC, merged